language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pedrokohler/multi-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pedrokohler/multi-client npm run test --coverage

after_success:
  - docker build -t pedrokohler/multi-client ./client
  - docker build -t pedrokohler/multi-nginx ./nginx
  - docker build -t pedrokohler/multi-server ./server
  - docker build -t pedrokohler/multi-worker ./worker
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push pedrokohler/multi-client
  - docker push pedrokohler/multi-nginx
  - docker push pedrokohler/multi-server
  - docker push pedrokohler/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'sa-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-sa-east-1-670702759269'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY