language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pedrokohler/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pedrokohler/react-test npm run test --coverage

after_success:
  - docker build -t pedrokohler/multi-client ./client
  - docker build -t pedrokohler/multi-nginx ./nginx
  - docker build -t pedrokohler/multi-server ./server
  - docker build -t pedrokohler/multi-worker ./worker
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push pedrokohler/multi-client
  - docker push pedrokohler/multi-nginx
  - docker push pedrokohler/multi-server
  - docker push pedrokohler/multi-worker